In [1]:
import ROOT
import root_numpy as rnpy
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn
import pickle
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.layers import LSTM

Welcome to ROOTaaS 6.06/08


Using Theano backend.


In [2]:
# build here the keras model
def RNN_classifier():
    model = Sequential()
    
    model.add(LSTM(32, input_shape = (None, 8)))
    
    # make an output layer with just 1 output -> for a binary classification problem: b-jet / not b-jet
    model.add(Dense(1, activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
  
    return model

In [3]:
def prepare_training_data(jet_list, label):
    # extract the tracks and put them in pt-order, hardest tracks first
    jet_tracks = [cur[-1] for cur in jet_list]
    jet_tracks = [sorted(cur, key = lambda tracks: tracks[0], reverse = True) for cur in jet_tracks]
    
    # zero-pad the track dimension, to make sure all jets fed into the network during training have the same length
    max_tracks = max([len(cur) for cur in jet_tracks])
    padded = [np.vstack([cur, np.full((max_tracks - len(cur), 8), 0, float)]) for cur in jet_tracks]
    
    batch_size = len(padded)
    timestep_size = max_tracks
    jet_dim = 8
    x_train = np.array(padded).reshape(batch_size, timestep_size, jet_dim)
    y_train = np.full((batch_size, 1), label, float) # all are b-jets!
    
    return x_train, y_train, batch_size

In [37]:
batch_size_jets = 100
batch_size_tracks = 320
read_pos_jets = 0
read_pos_tracks = 0
number_chunks = 0
chunks_limit = 1

In [38]:
model = RNN_classifier()

In [39]:
while number_chunks < chunks_limit:
    number_chunks += 1
    
    # read in new chunk of jet and track data
    #d1 = pd.DataFrame(rnpy.root2array("/mnt/t3nfs01/data01/shome/jpata/btv/gc/TagVarExtractor/GCa08e5e237323/TT_TuneCUETP8M1_13TeV-powheg-pythia8/job_0_out.root",
    #                            treename = "tagVars/ttree", start = read_pos_jets, stop = read_pos_jets + batch_size_jets))
    #d2 = pd.DataFrame(rnpy.root2array("/mnt/t3nfs01/data01/shome/jpata/btv/gc/TagVarExtractor/GCa08e5e237323/TT_TuneCUETP8M1_13TeV-powheg-pythia8/job_0_out.root",
    #                            treename = "tagVars/ttree_track", start = read_pos_tracks, stop = read_pos_tracks + batch_size_tracks))
    
    d1 = pd.read_hdf('../data/not_matched/1.h5', key = 'jets', start = read_pos_jets, stop = read_pos_jets + batch_size_jets)
    d1 = d1.reset_index(drop=True)
    
    d2 = pd.read_hdf('../data/not_matched/1.h5', key = 'tracks', start = read_pos_tracks, stop = read_pos_tracks + batch_size_tracks)
    d2 = d2.reset_index(drop=True)
    
    # break if we reached the end of the file
    if len(d1) < batch_size_jets:
        break;
        
    if len(d2) < batch_size_tracks:
        break;
    
    # figure out where the next chunk should start so that we don't count any jets multiple times
    last_tracks = (int)(d2.tail(1)['Track_jetIndex'].iloc[0]-1)
    last_jet = (int)(d1.tail(1)['Jet_jetIndex'].iloc[0]-1)
    
    # find the latest jet index thatis fully contained in this chunk
    while(len(d2.loc[d2['Track_jetIndex'] == last_tracks]) == 0):
        last_tracks -= 1
        
    if last_tracks > last_jet:
        print("Error: have more tracks than jets! Choose different chunk sizes!")
    
    read_pos_jets += (d1.loc[d1['Jet_jetIndex'] == last_tracks].index[-1] + 1)
    read_pos_tracks += (d2.loc[d2['Track_jetIndex'] == last_tracks].index[-1] + 1)

    # add the track data to the jet list
    d1['track_data'] = pd.np.empty((len(d1.index),0)).tolist()
    
    # iterate over the track list to join jets with the tracks belonging to them
    for irow, row in d2.iterrows():
        # these are the track data of the current track:
        tracks = row[["Track_pt", "Track_eta", "Track_phi", "Track_dxy", "Track_dz", "Track_IP", "Track_IP2D", "Track_length"]].as_matrix()
        jet_index = int(row["Track_jetIndex"])
        if jet_index > last_tracks:
            break
        table_index = d1.loc[d1['Jet_jetIndex'] == jet_index].index[0]

        # append the tracks data to the matching jet in the main table
        d1['track_data'][table_index].append(tracks)
    
    # now divide the jets and put them in separate lists, according to their flavour
    jets_b = []
    jets_l = []
    jets_c = []

    # iterate over the jet list, with already matched tracks
    for irow, row in d1.iterrows():
        jet_index = int(row["Jet_jetIndex"])
        if jet_index > last_tracks:
            break

        flavour = int(row["Jet_flavour"])

        # select the right list this jet belongs to
        if abs(flavour) == 5:
            jets = jets_b
        elif abs(flavour) == 4:
            jets = jets_c
        else:
            jets = jets_l

        # add the new jet to the list, if it contains any resolved tracks
        if len(row["track_data"]) > 0:
            jets += [(row["Jet_pt"], row["Jet_eta"], row["Jet_phi"], row["Jet_mass"], flavour, row["track_data"])]
        
    # now, have sorted jets in three lists, can use them directly for training!
    x_train_b, y_train_b, batch_size_b = prepare_training_data(jets_b, 1)
    x_train_c, y_train_c, batch_size_c = prepare_training_data(jets_c, 0)
    x_train_l, y_train_l, batch_size_l = prepare_training_data(jets_l, 0)
    history = model.fit(x_train_b, y_train_b, validation_split = 0.33, batch_size = batch_size_b, nb_epoch = 5)
    model.fit(x_train_c, y_train_c, validation_split = 0.33, batch_size = batch_size_c, nb_epoch = 5)
    model.fit(x_train_l, y_train_l, validation_split = 0.33, batch_size = batch_size_l, nb_epoch = 5)

Train on 15 samples, validate on 8 samples
Epoch 1/5
15/15 [==============================] - 0s - loss: 0.8615 - acc: 0.0000e+00 - val_loss: 0.8147 - val_acc: 0.2500
Epoch 2/5
15/15 [==============================] - 0s - loss: 0.8317 - acc: 0.0000e+00 - val_loss: 0.7898 - val_acc: 0.2500
Epoch 3/5
15/15 [==============================] - 0s - loss: 0.8034 - acc: 0.0000e+00 - val_loss: 0.7661 - val_acc: 0.2500
Epoch 4/5
15/15 [==============================] - 0s - loss: 0.7765 - acc: 0.0667 - val_loss: 0.7435 - val_acc: 0.2500
Epoch 5/5
15/15 [==============================] - 0s - loss: 0.7510 - acc: 0.0667 - val_loss: 0.7218 - val_acc: 0.2500
Train on 8 samples, validate on 4 samples
Epoch 1/5
8/8 [==============================] - 0s - loss: 0.6397 - acc: 1.0000 - val_loss: 0.6873 - val_acc: 0.5000
Epoch 2/5
8/8 [==============================] - 0s - loss: 0.6514 - acc: 0.8750 - val_loss: 0.6914 - val_acc: 0.5000
Epoch 3/5
8/8 [==============================] - 0s - loss: 0.6560 

In [26]:
# save the model after training here
model.save('./RNNtest2.h5')

In [44]:
d1['track_data'][0]

[array([ 2.94921875, -0.31513414, -2.41892505, -0.0234375 , -0.05398437,
         0.05650066,  0.02343749,  0.24183288], dtype=float32),
 array([  1.00546875e+01,  -3.76293212e-01,  -2.76434135e+00,
          1.13964835e-02,  -1.11755379e-03,   1.14440946e-02,
          1.13964770e-02,   7.37814903e-02], dtype=float32),
 array([ 2.63867188, -0.47462386, -2.40915179, -0.01628906,  0.01118164,
         0.0191297 ,  0.01628907,  0.10055161], dtype=float32),
 array([  1.65332031e+00,  -4.99343842e-01,  -2.66755581e+00,
          8.39843764e-04,   6.08886732e-03,   5.46604441e-03,
          8.39839515e-04,   4.63350080e-02], dtype=float32)]

In [41]:
x_train_b.shape

(23, 9, 8)

In [47]:
x_train_l[13]

array([[  7.76562500e+00,  -5.56291401e-01,  -2.46355295e+00,
         -3.71582038e-03,  -2.20214855e-03,  -4.17350652e-03,
         -3.71581782e-03,   5.02888933e-02],
       [  2.01953125e+00,  -5.23880720e-01,  -2.15045142e+00,
         -2.13470455e-04,  -3.21289059e-03,   2.82542314e-03,
          2.13470572e-04,   3.04736639e-03],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.0